package coop.stlma.tech.protocolsn.blogplugin.data.entity;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;
import java.util.UUID;

/**
 * Database entity representing a registered plugin.
 *
 * @author John Meyerin
 */
@Entity
@Table(name = "blog_entry")
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
public class BlogEntryEntity {

    /**
     * Autogenerated UUID serving as the primary key.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * ID of the user who authored this blog
     */
    @Column(name = "author")
    private UUID author;

    /**
     * Title of this blog entry
     */
    @Column(name = "blog_title")
    private String blogTitle;

    /**
     * Text of this blog entry
     */
    @Column(name = "blog_text")
    private String blogText;

    /**
     * Comma-separated list of tags
     */
    @Column(name = "tags")
    private String tags;

    /**
     * When this blog entry was created
     */
    @Column(name = "created_at")
    @CreationTimestamp
    private Instant createdAt;

    /**
     * When this blog entry was last updated
     */
    @Column(name = "updated_at")
    @UpdateTimestamp
    private Instant updatedAt;
}
