micronaut:
  server:
    port: 8080
    context-path: /blog
  security:
    oauth2:
      clients:
        keycloak:
          openid:
            issuer: http://keycloak:8080/realms/social-network-ecosystem
        keycloak-client:
          token:
            url: http://keycloak:8080/realms/social-network-ecosystem/protocol/openid-connect/token
          openid:
            issuer: http://keycloak:8080/realms/social-network-ecosystem

coop:
  stlma:
    tech:
      protocolsn:
        plugin-name: ProtocolSNBlogPlugin
        plugin-target: dns:///psn-blog-plugin:50051

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none

flyway:
  datasources:
    default:
      enabled: true
      locations: db/migrations

datasources:
  default:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://db:5432/blogplugin
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:postgres}
    dialect: POSTGRES

grpc:
  server:
    port: 50051
  channels:
    node-manager:
      plaintext: true
      target: psn-node-manager:50051

logger:
  levels:
    io.micronaut.http: TRACE
    io.micronaut.security: DEBUG