micronaut:
  application:
    name: ProtocolSNBlogPlugin
  server:
    cors:
      enabled: true
    port: 8082
    context-path: /
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        mapping: /swagger-ui/**
        paths: classpath:META-INF/swagger/views/swagger-ui
  security:
#    token:
#      jwt:
#        signatures:
#          jwks:
#            keycloak:
#              url: http://localhost:9080/auth/realms/social-network-ecosystem/protocol/openid-connect/certs
    oauth2:
      clients:
        keycloak:
          client-id: blog-plugin
          client-secret: blog-plugin-secret

          openid:
            issuer: http://localhost:9080/auth/realms/social-network-ecosystem
    endpoints:
      logout:
        get-allowed: true
    authentication: idtoken
    intercept-url-map:
      - pattern: /swagger/**
        access: isAnonymous()
      - pattern: /swagger-ui/**
        access: isAnonymous()
  openapi:
    enabled: true

coop:
  stlma:
    tech:
      protocolsn:
        plugin-name: ProtocolSNBlogPlugin
        plugin-target: dns:///localhost:50053

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none

flyway:
  datasources:
    default:
      enabled: true
      locations: db/migrations

datasources:
  default:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5443/blogplugin
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:postgres}
    dialect: POSTGRES

grpc:
  server:
    port: 8092
  channels:
    node-manager:
      plaintext: true
      target: localhost:50051