swagger-ui.enabled=true
micronaut.openapi.views.spec=apidoc.enabled=true,swagger-ui.enabled=true,swagger-ui.theme=flattop
micronaut.openapi.expand.api.version=v0.3.0
micronaut.openapi.expand.openapi.description=ProtocolSN Blog Plugin API